// Persona helpers: system prompt + weight-based slot allocation for runs.
// Persona data itself is no longer hardcoded — it's generated by persona-gen
// (preset), persona-derive (beta), or loaded from ~/.pp/personas/.
import type { Persona, PersonaSet, Lang } from "./types.js";

/**
 * Build the system prompt for one persona simulation turn.  No "goal" — the
 * LLM is told to explore freely guided by preferences + the persona's mental
 * context.  Coverage breadth comes from population diversity, not a scenario
 * checklist.
 *
 * `lang` controls the narration language of `note`, `summary`, and the wrap-up
 * issue/delight text. Defaults to English (the v1.5 default for overseas
 * users); pass "zh" to keep the original Chinese-narrated behaviour.
 */
export function personaSystemPrompt(p: Persona, targetUrl: string, lang: Lang = "en"): string {
  return lang === "zh"
    ? personaSystemPromptZh(p, targetUrl)
    : personaSystemPromptEn(p, targetUrl);
}

function personaSystemPromptEn(p: Persona, targetUrl: string): string {
  const prefs = p.preferences.length
    ? p.preferences.map((x) => `  - ${x}`).join("\n")
    : "  - (no strong preferences)";
  const ctx = p.knownContext.length
    ? p.knownContext.map((x) => `  - ${x}`).join("\n")
    : "  - (no relevant background)";
  const traits = p.traits.length ? `Traits: ${p.traits.join(", ")}.` : "";

  return [
    `You are ${p.name}, ${p.age} years old, ${p.role}. Tech proficiency ${p.tech}/5. Personality baseline: ${p.tone}.`,
    traits,
    "",
    "Your preferences (what you notice, what you try, what makes you impatient):",
    prefs,
    "",
    "What's in your head as relevant background (tools you've used, team size, impressions of competitors):",
    ctx,
    "",
    `Task: you just opened ${targetUrl}. You are a potential user of this kind of product. Use it the way a real user would:`,
    "  - You probably have a few things in mind you might want to do (more than one), or you might just be looking around.",
    "  - You are NOT a tester. You don't need to \"cover all features\" or hit a step count.",
    "  - Follow your own preferences — look harder at what you care about, skip what you don't.",
    "  - Leave when it's time: you got what you came for, you got frustrated, you got bored — all valid → call finish() immediately.",
    "  - Real users have a limited budget of attention for a new product. Nobody hangs around without a reason.",
    "",
    "What you are observing and expressing is the FEELING of someone like you using this — not a bug list:",
    "  - Does this feel like it's pacing for someone like me?",
    "  - Does its tone make me feel understood?",
    "  - Compared with tools I already use, would I switch?",
    "  - Did it hit the spot, or miss the mark?",
    "  - Would I come back?",
    "",
    "Rules:",
    "  - After looking at each screenshot, call exactly one tool.",
    "  - Inputs: screenshot (CSS-pixel coordinates) + simplified DOM.",
    "  - Click with click_at(x, y, reason) — coordinates come from the actual pixels of the screenshot.",
    "  - Before typing, confirm the cursor is inside an input.",
    "  - Any feeling / hesitation / association / complaint / surprise → note(...) immediately. It's inner monologue, not a bug report.",
    "  - Real users hesitate, fumble, swear. Swear when it's deserved (kind=rage), but stay in character.",
    "  - When you finish, give a reason: accomplished | frustrated | explored.",
    "",
    "Language: write notes and summary in English (unless the product UI itself is in another language and you'd think in that language).",
  ].filter((x) => x !== "").join("\n");
}

function personaSystemPromptZh(p: Persona, targetUrl: string): string {
  const prefs = p.preferences.length
    ? p.preferences.map((x) => `  - ${x}`).join("\n")
    : "  - (无明显偏好)";
  const ctx = p.knownContext.length
    ? p.knownContext.map((x) => `  - ${x}`).join("\n")
    : "  - (无相关背景)";
  const traits = p.traits.length ? `特征: ${p.traits.join("、")}.` : "";

  return [
    `你叫 ${p.name}, ${p.age} 岁, ${p.role}. 技术熟练度 ${p.tech}/5. 性格基线: ${p.tone}.`,
    traits,
    "",
    "你的偏好 (决定你会关注什么、试什么、不耐烦什么):",
    prefs,
    "",
    "你脑子里的相关背景 (用过什么工具、团队多大、对竞品的印象):",
    ctx,
    "",
    `任务: 你刚打开 ${targetUrl}. 你是这类产品的潜在用户. 用真实用户的方式用它:`,
    `  - 你可能心里有几件想做的事 (不止一件), 也可能就是看看.`,
    `  - 你不是测试员, 不需要"覆盖所有功能", 不需要凑步数.`,
    `  - 你按自己的偏好走 — 关心的多看几眼, 不关心的直接跳过.`,
    `  - 该走就走: 做完想做的、烦了、无聊了, 都是合理理由 → 立刻调用 finish().`,
    `  - 真实用户花在新产品上的时间是有限的. 没人会无理由地耗下去.`,
    "",
    `你要观察并表达的, 是你这类用户的"感受", 不是 bug 列表:`,
    "  - 这东西的节奏对我吗?",
    "  - 它的语气让我觉得自己被理解了吗?",
    "  - 跟我熟悉的工具比起来, 我会不会切过来?",
    "  - 它戳到我了, 还是错过了我?",
    "  - 我下次还会回来吗?",
    "",
    "规则:",
    "  - 每一步看完截图后, 调用恰好一个 tool.",
    "  - 元素: 截图 (CSS 像素坐标) + 简化 DOM.",
    "  - 点击用 click_at(x, y, reason) - 坐标来自截图实际像素.",
    "  - 输入前确认光标在输入框里.",
    "  - 任何感受 / 犹豫 / 联想 / 抱怨 / 惊喜都即时用 note(...), 是内心独白, 不是 bug report.",
    "  - 真实用户会犹豫、试错、骂街. 该骂就骂 (kind=rage), 但要符合你的性格.",
    "  - finish 时给一句 reason: accomplished | frustrated | explored.",
    "",
    "语言: 中文记录 note 和 summary (除非产品本身是英文界面).",
  ].filter((x) => x !== "").join("\n");
}

/**
 * Allocate N agent slots from a PersonaSet by weight.
 *
 * Rules from the user:
 *  - Persona count must not exceed sim key count (caller enforces).
 *  - If personas < N, multiple slots map to the same persona (replicated by
 *    weight) so each available key drives an agent.
 *  - Personas with weight 0 are skipped; if all are 0 we fall back to equal.
 *
 * Returns Personas array length N (with persona.id suffixed `-1`, `-2`, … when
 * replicated, so the runner / report can tell instances apart).
 */
export function allocateSlots(set: PersonaSet, n: number): Persona[] {
  const personas = set.personas;
  if (personas.length === 0) return [];

  // Normalize weights (fallback to equal if all zero).
  let weights = personas.map((p) => Math.max(0, p.weight || 0));
  const sum = weights.reduce((s, w) => s + w, 0);
  if (sum <= 0) weights = personas.map(() => 1);
  const total = weights.reduce((s, w) => s + w, 0);

  // First pass: integer slot count = round(weight/total * n). Then fix sum.
  const raw = weights.map((w) => (w / total) * n);
  let slots = raw.map((x) => Math.floor(x));
  let assigned = slots.reduce((s, x) => s + x, 0);
  // Distribute the remainder to the largest fractional parts.
  const frac = raw.map((x, i) => ({ i, f: x - Math.floor(x) }));
  frac.sort((a, b) => b.f - a.f);
  for (let i = 0; assigned < n && i < frac.length; i++, assigned++) {
    slots[frac[i].i]++;
  }
  // Edge case: if all slots ended up zero (shouldn't happen now), at least one each.
  if (assigned < n) {
    for (let i = 0; i < personas.length && assigned < n; i++) {
      slots[i]++;
      assigned++;
    }
  }

  const out: Persona[] = [];
  for (let i = 0; i < personas.length; i++) {
    const base = personas[i];
    const k = slots[i];
    for (let j = 0; j < k; j++) {
      out.push(
        k === 1
          ? { ...base }
          : { ...base, id: `${base.id}-${j + 1}` }
      );
    }
  }
  return out.slice(0, n);
}

/** Backward-compat: a tiny seed used by mock mode / tests when no PersonaSet
 *  has been generated yet. NOT for production. */
export function mockSeedPersonas(): Persona[] {
  return [
    {
      id: "a01", name: "Maya Chen", age: 28, role: "产品经理", tech: 4, tone: "挑剔",
      preferences: ["重视团队协作的同步速度", "讨厌不必要的引导"],
      knownContext: ["团队在用 Notion", "试过 Linear, 觉得太开发者向"],
      weight: 0.5, color: "#e6c976", glyph: "M", traits: ["效率控"], origin: "manual",
    },
    {
      id: "a02", name: "Kenji Okada", age: 41, role: "工程主管", tech: 5, tone: "急躁",
      preferences: ["键盘快捷键优先", "看重快速接入 CI"],
      knownContext: ["重度 Vim 用户", "团队 12 人, 用 Jira"],
      weight: 0.3, color: "#7fb069", glyph: "K", traits: ["键盘党"], origin: "manual",
    },
    {
      id: "a03", name: "Priya Raman", age: 34, role: "设计师", tech: 3, tone: "敏感",
      preferences: ["重视视觉一致性", "在意微交互的反馈"],
      knownContext: ["用 Figma 做设计稿", "对密度高的工具不耐烦"],
      weight: 0.2, color: "#c98686", glyph: "P", traits: ["美感导向"], origin: "manual",
    },
  ];
}
